# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
  - container: linux
    image: registry.fedoraproject.org/fedora-minimal:34

stages:
  - stage: prep
    jobs:
      - job: fetch-git-repo
        steps:
          - script: dnf in -y git
          - script: git clone https://github.com/ultramarine-linux/ultramarine-kickstarts.git --depth 1
          - script: cd ultramarine-kickstarts
          - script: bash ./builddeps.sh
  - stage: base-image
    jobs:
      - job: lorax-build
        steps:
          - script: bash ./build-lorax.sh
  - stage: image
    jobs:
      - job: iso-build
        steps:
          - script: bash ./build.sh
          - publish: ./build/*.iso
            artifact: live-image-cyber
            displayName: Cyber Desktop