[image]
releasever = 36
name = "ultramarine"

[variant-flagship]
kickstart="kickstarts/ultramarine-budgie.ks"
type="iso"

[variant-cutefish]
kickstart="kickstarts/ultramarine-cutefish.ks"
type="iso"

[variant-pantheon]
kickstart="kickstarts/ultramarine-pantheon.ks"
type="iso"

[variant-gnome]
kickstart="kickstarts/ultramarine-gnome.ks"
type="iso"

[variant-plasma]
kickstart="kickstarts/ultramarine-plasma.ks"
type="iso"

[variant-podman]
kickstart="kickstarts/ultramarine-docker.ks"
type="podman"