name: Build ISO images
on:
  push:
    branches:
      - um38
    paths:
      - "kickstarts/**"
      - "!kickstarts/docker/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        variant:
          - budgie
          - gnome
          - pantheon
          - plasma
    container:
      image: fedora:38
      options: --cap-add=SYS_ADMIN --privileged -v /dev:/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra38.repo
          sudo dnf install -y lorax-lmc-novirt pykickstart make
      - name: Build ISO
        run: |
          ./build.sh ${{ matrix.variant }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}-${{ matrix.arch }}
          path: build/
  deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/download-artifact@v3
      - name: Test
        run: |
          ls
