name: Build ISO images
on:
  push:
    branches:
      - um38
    paths:
      - "kickstarts/**"
      - "!kickstarts/docker/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        variant:
          - budgie
          - gnome
          - pantheon
          - plasma
    container:
      image: fedora:38
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - run: ls /dev
      - run: losetup -f
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra38.repo
          sudo dnf install -y lorax-lmc-novirt pykickstart make
      - name: Build ISO
        run: |
          ./build.sh ${{ matrix.variant }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}-${{ matrix.arch }}
          path: build/
  deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/download-artifact@v3
      - name: Prepare images directory
        run: |
          mkdir -p images
          variants=(budgie gnome pantheon plasma)
          archs=(x86_64 aarch64)

          for variant in "${variants[@]}"; do
            for arch in "${archs[@]}"; do
              mv ${variant}-${arch}/images/*.iso images/${variant}-${arch}.iso
              sha256sum images/${variant}-${arch}.iso > images/${variant}-${arch}.iso.sha256sum
            done
          done
      - name: Upload to R2
        uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          aws_key_id: ${{ secrets.S3_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_KEY }}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: "images"
          destination_dir: isos/ultramarine/38/
