name: Build ISO images (with Katsu)

env:
  DNF_PKGS: |
    git
    xorriso
    rpm
    limine
    systemd
    btrfs-progs
    e2fsprogs
    xfsprogs
    dosfstools
    grub2
    parted
    util-linux-core
    systemd-container
    grub2-efi
    uboot-images-armv8
    uboot-tools
    rustc
    qemu-user-static-aarch64
    qemu-user-binfmt
    qemu-kvm
    qemu-img
    cargo
    systemd-devel
    mkpasswd
    clang-devel
    moby-engine
    squashfs-tools
    erofs-utils
    grub2-tools
    grub2-tools-extra
    isomd5sum

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - flagship
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
      # Pass /dev from host to container
      # Very hacky, but it works
      # Microsoft/Github, if you're reading this,
      # I'm sorry.
      options: --privileged -v /dev:/dev

    steps:
      - name: Install dependencies
        run: |
          dnf install -y $DNF_PKGS
          dnf clean all
      - name: Clone Katsu
        uses: actions/checkout@v3
        with:
          repository: FyraLabs/katsu
          ref: main
          path: katsu
      - name: Build Katsu
        run: |
          pushd katsu
          cargo build --release
          cp target/release/katsu /usr/bin/katsu
          popd
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ISO
        run: |
          pushd katsu
          katsu --output=iso ${{ matrix.variant }}-live.yaml
