name: Docker Image
on:
  push:
    branches:
      - lapis
    paths:
      - kickstarts/docker/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ARM64
        variant:
          - docker
          - docker-minimal
    runs-on: ${{ matrix.runner }}
    container:
      image: fedora:38
      options: --cap-add=SYS_ADMIN --privileged

    services:
      dind:
        image: docker:20.10.7-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra38.repo
          sudo dnf install -y lorax-lmc-novirt pykickstart make moby-engine
      # upload image to ghcr.io
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        env:
          releasever: 38
        run: |
          ./build.sh -p ${{ matrix.variant }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}-${{ matrix.arch }}
          path: build/
