name: Docker Image
on:
  push:
    branches:
      - lapis
    paths:
      - kickstarts/ultramarine-docker.ks
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        variant:
          - docker
    container:
      image: fedora:37
      options: --cap-add=SYS_ADMIN --privileged

    services:
      dind:
        image: docker:20.10.7-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/ad37.repo
          sudo dnf install -y lorax-lmc-novirt pykickstart make moby-engine
      - name: Build ISO
        run: |
          ./build.sh ${{ matrix.variant }}

      # upload image to ghcr.io
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # docker import base image
      - name: Import image
        if: ${{ matrix.variant == 'docker' }}
        run: |
          docker tag ultramarine:37 ultramarine:latest
          docker tag ultramarine:37 ghcr.io/ultramarine-linux/ultramarine:37
          docker tag ultramarine:37 ghcr.io/ultramarine-linux/ultramarine:latest
          docker push ghcr.io/ultramarine-linux/ultramarine:37

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}-${{ matrix.arch }}
          path: build/
