name: Ultramarine Linux ISO build integration testing

on:
  push:
    branches:
      - lapis

env:
  GHCR_USER: ${{ secrets.GHCR_USER }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  login:
    name: Log into GitHub Container Registry
    runs-on: self-hosted
    steps:
      - name: Log into ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}
          registry: ${{ env.IMAGE_REGISTRY }}
  build:
    name: ISO Builder
    runs-on: self-hosted
    container:
      image: ghcr.io/ultramarine-linux/installer-buildenv:34 # finally
      volumes:
        - /home/common/files:/files
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'lapis'
      - name: Building the ISO...
        run: ./build.sh 'kickstarts/ultramarine-cyber.ks' 'Ultramarine Linux Cyber' 'Ultramarine-Linux-Cyber-Live'
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux Cyber x86_64 ISO
          path: ./build/*.iso
