name: Ultramarine Linux 34 Cyber x86_64 ISO Build

on:
  push:
    branches:
      - lapis

jobs:
  build:
    name: ISO Builder
    runs-on: self-hosted
    container:
      image: ghcr.io/ultramarine-linux/installer-buildenv:34 # finally
      credentials:
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
      volumes:
        - /home/common/files:/files
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'lapis'
      - name: Fetch Dependencies
        run: microdnf install livecd-tools    
      - name: Building the ISO...
        run: livecd-creator -c kickstarts/ultramarine-cyber.ks -f Ultramarine-Linux-Live
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux Cyber x86_64 ISO
          path: ./*.iso
