name: Ultramarine Linux 34 Cyber x86_64 ISO Build

on:
  push:
    branches:
      - lapis

jobs:
  build:
    name: ISO Builder
    runs-on: self-hosted
    container:
      image: ghcr.io/ultramarine-linux/installer-buildenv:34 # finally
      options: --privileged
      volumes:
      - /files:/home/common/files
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'lapis'
      - name: Building the ISO...
        run: ./build.sh 'kickstarts/ultramarine-cyber.ks' 'Ultramarine Linux Cyber' 'Ultramarine-Linux-Cyber-Live'
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux Cyber x86_64 ISO
          path: ./build/*.iso
