name: Ultramarine Linux 34 Cyber x86_64 ISO Build

on:
  push:
    branches:
      - lapis

jobs:
  build:
    name: ISO Builder
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Cloning Git repo...
        run: |
          sudo dnf in -y git
          git clone https://github.com/ultramarine-linux/ultramarine-kickstarts.git
          cd ultramarine-kickstarts
      - name: Installing dependencies
        run: ./builddeps.sh
      - name: Building the base Lorax image...
        run: ./build-lorax.sh '34' 'x86_64'
      - name: Building the ISO...
        run: ./build.sh 'kickstarts/ultramarine-cyber.ks' 'Ultramarine Linux Cyber' 'Ultramarine-Linux-Cyber-Live'
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux Cyber x86_64 ISO
          path: ./build/*.iso
