name: Ultramarine Linux 34 Cyber x86_64 ISO Build

on:
  push:
    branches:
      - lapis

jobs:
  build:
    name: ISO Builder
    runs-on: self-hosted
    container:
      image: registry.fedoraproject.org/fedora:34-x86_64
      options: --privileged
      volumes:
      - /home/common/files:/files
    steps:
      - uses: actions/checkout@v2
      - name: Cloning Git repo...
        run: ls
      - name: Installing dependencies
        run: ./builddeps.sh
      - name: Building the ISO...
        run: ./build.sh 'kickstarts/ultramarine-cyber.ks' 'Ultramarine Linux Cyber' 'Ultramarine-Linux-Cyber-Live'
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux Cyber x86_64 ISO
          path: ./build/*.iso
