name: Ultramarine Linux ISO Build

on:
  push:
    branches:
      - mainproblem

jobs:
  build:
    name: ISO Builder
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Cloning Git repo...
        run: |
          sudo dnf in -y git
          git clone https://github.com/ultramarine-linux/ultramarine-kickstarts.git
          cd ultramarine-kickstarts
      - name: Installing dependencies
        run: ./builddeps.sh
      - name: Building the base Lorax image...
        run: ./build-lorax.sh
      - name: Building the ISO...
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Ultramarine Linux ISO
          path: ./build/*.iso
